// A practical list of US cities/states for autocomplete.
// Not exhaustive — covers state capitals + major metro areas, which covers
// the vast majority of independent dental practice locations. Free text
// entry still works if a city isn't in this list.
export const US_CITIES = [
  "New York, NY", "Buffalo, NY", "Rochester, NY", "Albany, NY", "Syracuse, NY",
  "Los Angeles, CA", "San Diego, CA", "San Jose, CA", "San Francisco, CA", "Fresno, CA", "Sacramento, CA", "Long Beach, CA", "Oakland, CA", "Bakersfield, CA", "Anaheim, CA",
  "Chicago, IL", "Aurora, IL", "Naperville, IL", "Springfield, IL", "Rockford, IL",
  "Houston, TX", "San Antonio, TX", "Dallas, TX", "Austin, TX", "Fort Worth, TX", "El Paso, TX", "Arlington, TX", "Corpus Christi, TX", "Plano, TX", "Lubbock, TX",
  "Phoenix, AZ", "Tucson, AZ", "Mesa, AZ", "Chandler, AZ", "Scottsdale, AZ", "Glendale, AZ",
  "Philadelphia, PA", "Pittsburgh, PA", "Allentown, PA", "Harrisburg, PA", "Erie, PA",
  "San Antonio, TX", "Jacksonville, FL", "Miami, FL", "Tampa, FL", "Orlando, FL", "St. Petersburg, FL", "Tallahassee, FL", "Fort Lauderdale, FL", "Cape Coral, FL",
  "Columbus, OH", "Cleveland, OH", "Cincinnati, OH", "Toledo, OH", "Akron, OH", "Dayton, OH",
  "Charlotte, NC", "Raleigh, NC", "Greensboro, NC", "Durham, NC", "Winston-Salem, NC", "Asheville, NC",
  "Indianapolis, IN", "Fort Wayne, IN", "Evansville, IN", "South Bend, IN",
  "Seattle, WA", "Spokane, WA", "Tacoma, WA", "Vancouver, WA", "Bellevue, WA",
  "Denver, CO", "Colorado Springs, CO", "Aurora, CO", "Fort Collins, CO", "Boulder, CO",
  "Washington, DC",
  "Boston, MA", "Worcester, MA", "Springfield, MA", "Cambridge, MA", "Lowell, MA",
  "Nashville, TN", "Memphis, TN", "Knoxville, TN", "Chattanooga, TN", "Clarksville, TN",
  "Detroit, MI", "Grand Rapids, MI", "Warren, MI", "Sterling Heights, MI", "Ann Arbor, MI", "Lansing, MI",
  "Portland, OR", "Salem, OR", "Eugene, OR", "Bend, OR",
  "Las Vegas, NV", "Henderson, NV", "Reno, NV", "Carson City, NV",
  "Louisville, KY", "Lexington, KY", "Bowling Green, KY", "Frankfort, KY",
  "Baltimore, MD", "Annapolis, MD", "Frederick, MD", "Rockville, MD",
  "Milwaukee, WI", "Madison, WI", "Green Bay, WI", "Kenosha, WI",
  "Albuquerque, NM", "Santa Fe, NM", "Las Cruces, NM",
  "Tucson, AZ", "Salt Lake City, UT", "Provo, UT", "Ogden, UT",
  "Kansas City, MO", "St. Louis, MO", "Springfield, MO", "Columbia, MO", "Jefferson City, MO",
  "Atlanta, GA", "Augusta, GA", "Columbus, GA", "Savannah, GA", "Athens, GA",
  "Oklahoma City, OK", "Tulsa, OK", "Norman, OK", "Broken Arrow, OK",
  "Omaha, NE", "Lincoln, NE",
  "Minneapolis, MN", "St. Paul, MN", "Rochester, MN", "Duluth, MN",
  "New Orleans, LA", "Baton Rouge, LA", "Shreveport, LA", "Lafayette, LA",
  "Richmond, VA", "Virginia Beach, VA", "Norfolk, VA", "Arlington, VA", "Chesapeake, VA",
  "Birmingham, AL", "Montgomery, AL", "Huntsville, AL", "Mobile, AL",
  "Boise, ID", "Meridian, ID", "Nampa, ID",
  "Des Moines, IA", "Cedar Rapids, IA", "Davenport, IA",
  "Little Rock, AR", "Fayetteville, AR", "Fort Smith, AR",
  "Jackson, MS", "Gulfport, MS", "Biloxi, MS",
  "Wichita, KS", "Overland Park, KS", "Topeka, KS", "Kansas City, KS",
  "Providence, RI", "Warwick, RI",
  "Hartford, CT", "New Haven, CT", "Stamford, CT", "Bridgeport, CT",
  "Manchester, NH", "Concord, NH", "Nashua, NH",
  "Burlington, VT", "Montpelier, VT",
  "Portland, ME", "Augusta, ME", "Bangor, ME",
  "Wilmington, DE", "Dover, DE",
  "Charleston, WV", "Huntington, WV", "Morgantown, WV",
  "Anchorage, AK", "Juneau, AK", "Fairbanks, AK",
  "Honolulu, HI", "Hilo, HI",
  "Sioux Falls, SD", "Rapid City, SD", "Pierre, SD",
  "Fargo, ND", "Bismarck, ND",
  "Billings, MT", "Missoula, MT", "Helena, MT",
  "Cheyenne, WY", "Casper, WY",
  "Charleston, SC", "Columbia, SC", "Greenville, SC", "North Charleston, SC",
];
